openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Contacts App"
paths:
  /account/login:
    put:
      summary: Perform a login
      tags:
        - Account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                  format: password
      responses:
        200:
          description: Log in successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
              example:
                name: Bob Smith
                email: bob@fake.com
                phone: 555-555-5555
                imagePath: '/contacts/123456/image'
        401:
          description: Unauthorized
  /account/logout:
    get:
      summary: Perform a logout
      tags:
        - Account
      responses:
        200:
          description: Log out successful.
  /account/change-password:
    post:
      summary: Change your password
      tags:
        - Account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                oldPassword:
                  type: string
                  format: password
                newPassword:
                  type: string
                  format: password
      responses:
        200:
          description: Password updated
        400:
          description: Old password incorrect
  /account/register:
    post:
      summary: Create an account
      tags:
        - Account
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                  format: password
      responses:
        200:
          description: Account created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
              example:
                name: Bob Smith
                email: bob@fake.com
                phone: 555-555-5555
                imagePath: '/contacts/123456/image'
        409:
          description: Account already exists
  /contacts:
    get:
      summary: Get your own contacts
      tags:
        - Contacts
      responses:
        200:
          description: Get an array of your contacts.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contact'
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /contacts/{contactId}:
    parameters:
      - name: contactId
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get details about a single contact
      tags:
        - Contacts
      responses:
        200:
          description: Get details about a single contact
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
              example:
                name: Bob Smith
                email: bob@fake.com
                phone: 555-555-5555
                imagePath: '/contacts/123456/image'
        401:
          description: Unauthorized
        403:
          description: Forbidden
    put:
      summary: Make a contact
      tags:
        - Contacts
      responses:
        200:
          description: Contact made.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
              example:
                name: Bob Smith
                email: bob@fake.com
                phone: 555-555-5555
                imagePath: '/contacts/123456/image'
        401:
          description: Unauthorized
        403:
          description: Forbidden
    delete:
      summary: Remove a contact
      tags:
        - Contacts
      responses:
        204:
          description: Contact removed.
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /contacts/{contactId}/image:
    parameters:
      - name: contactId
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get a contact's picture
      tags:
        - Contacts
      responses:
        200:
          description: Retrieved contact's picture
        401:
          description: Unauthorized
        403:
          description: Forbidden
  /profile:
    get:
      summary: Get your own profile information
      tags:
        - Profile
      responses:
        200:
          description: Profile info retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
              example:
                name: Bob Smith
                email: bob@fake.com
                phone: 555-555-5555
                imagePath: '/contacts/123456/image'
    put:
      summary: Set profile information
      tags:
        - Profile
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
      responses:
        200:
          description: Profile info saved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
              example:
                name: Bob Smith
                email: bob@fake.com
                phone: 555-555-5555
                imagePath: '/contacts/123456/image'
  /profile/image:
    get:
      summary: Get your profile picture
      tags:
        - Profile
      responses:
        200:
          description: Retrieved profile picture
    put:
      summary: Set your profile picture
      tags:
        - Profile
      responses:
        200:
          description: Set profile picture
components:
  examples:
    ContactSimple:
      value:
        name: Bob Smith
        email: bob@fake.com
        phone: 555-555-5555
    ContactDetails:
      value:
        name: Bob Smith
        email: bob@fake.com
        phone: 555-555-5555
        imagePath: '/contacts/123456/image'
  schemas:
    Contact:
      type: object
      required:
        - name
        - email
        - phone
      properties:
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        imageUrl:
          type: string
      example:
        $ref: '#/components/examples/ContactSimple'